adjective = input("Введите прилагательное: ")
noun = input("Введите существительное: ")
verb = input("Введите глагол в прошедшем времени: ")
animal = input("На какое животное? ")
print("Ваша чепуха: ")
print(f'Этот {adjective} {noun} {verb} {animal}')
